pr:
  branches:
    include:
    - '*'
    exclude:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Module Tests'
    backendAzureRmResourceGroupName: 'Terraform-Storage-accountRG'
    backendAzureRmStorageAccountName: 'softcattfmodulestate'
    backendAzureRmContainerName: 'tf-modules-azure-recovery-services-vault'
    backendAzureRmKey: 'terraform.tfstate'