pr:
  branches:
    include:
    - '*'
    exclude:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

# - bash: | 
#     terraform init
#     terraform plan


- task: TerraformTaskV2@2
  displayName: Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Module Tests'
    backendAzureRmResourceGroupName: 'Terraform-Storage-accountRG'
    backendAzureRmStorageAccountName: 'softcattfmodulestate'
    backendAzureRmContainerName: 'tf-modules-azure-recovery-services-vault'
    backendAzureRmKey: 'terraform.tfstate'
    
- task: TerraformTaskV2@2
  displayName: 'validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV2@2
  displayName: 'plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Module Tests'