pr:
  branches:
    include:
    - '*'
    exclude:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  displayName: Init Basic
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'tests/basic/'
    backendServiceArm: 'Module Tests'
    backendAzureRmResourceGroupName: 'Terraform-Storage-accountRG'
    backendAzureRmStorageAccountName: 'softcattfmodulestate'
    backendAzureRmContainerName: 'tf-modules-azure-recovery-services-vault'
    backendAzureRmKey: 'terraform.tfstate'
    
- task: TerraformTaskV2@2
  displayName: Validate Basic
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: 'tests/basic/'


- task: TerraformTaskV2@2
  displayName: Plan Basic
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'tests/basic/'
    environmentServiceNameAzureRM: 'Module Tests'