name: test

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: >
      {
        "clientId": "${{ secrets.SANDBOX_AZURE_CLIENT_ID }}",
        "clientSecret": "${{ secrets.SANDBOX_AZURE_CLIENT_SECRET }}",
        "subscriptionId": "${{ secrets.SANDBOX_AZURE_SUBSCRIPTION_ID }}",
        "tenantId": "${{ secrets.SANDBOX_AZURE_TENANT_ID }}"
      }

jobs:
  get:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: echo
        run: echo "${{ env.AZURE_CREDENTIALS }}" >> creds.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: creds.txt
